### ISSUE TITLE
Timestamp unit

### ISSUE THREAD

**Issue by awr-richard** [nkaz001/hftbacktest#10]
Hi - minor comment re the docs, I believe the timestamp unit is expected to be in microseconds but I don't see that mentioned in the documentation. It took a few minutes to figure out i had the wrong units for timestamp when i was trying an example, probably worth mentioning.
thanks
Richard

**Comment by nkaz001** [comment]
Thanks for the feedback. There is still a lack of documentation. I'll work on that as well.
You need to ensure that all timestamp units you use are the same as the timestamp unit in your data. It doesn't have to be in microseconds.

**Comment by nkaz001** [comment]
Finally, update the docs. please see https://hftbacktest.readthedocs.io/en/latest/index.html

**Comment by awr-richard** [comment]
> Finally, update the docs. please see https://hftbacktest.readthedocs.io/en/latest/index.html

thanks!
