### ISSUE TITLE
Remove 'rust' sub-directory from the repo

### ISSUE THREAD

**Issue by tradflux** [nkaz001/hftbacktest#118]
Looks to me like we don't need it. If I'm intepreting the directory structure correctly we're going to end up with;

1. hftbacktest
2. hftbacktest-derive
3. py-hftbacktest

I know there isn't anything except the MD file but the simpler the better I think.

**Comment by nkaz001** [comment]
I left that directory because there is still a lot of traffic to that URL. I don't want visitors to encounter a 404 error. But, it will be removed in the future.
