### ISSUE TITLE
simple_two_sided_quote query

### ISSUE THREAD

**Issue by griffiri** [nkaz001/hftbacktest#12]
Hi - to better understand the library I took a very small data sample (one minute of data, about 50 book updates and a few trades, in the attached archive) and tried to run it through the simple_two_quote function you have on the main page of the project. I've put a self contained script here https://gist.github.com/griffiri/12898ab4684e0d63375c8ea6dafabfa1, to run it you need to put the extracted contents of the archive into the same directory as the script.

When running the script in the first elapsed time interval orders are submitted as expected, then in the second elapsed time interval orders are submitted again. As the price in tick units has not changed the 'order id' has not changed. After this a duplicate order id error is thrown (error below). I thought the issue might be that the same order id is used, but the open orders are cancelled before the new orders are placed. Then I thought it might be because the new orders are placed before the exchange has had a chance to process the cancel, so I modified the script to use the ```wait=True``` option when cancelling the order. That does seem to process the cancel on the exchange side, but I don't see the cancel processed on the local side and I get the same error. I started looking into why but thought it might better to ask at this point, in case I am on the wrong track. 

```python
Traceback (most recent call last):
  File "/Users/richardgriffiths/projects/hftbacktest/examples/run_simple.py", line 115, in <module>
    run()
  File "/Users/richardgriffiths/projects/hftbacktest/examples/run_simple.py", line 109, in run
    simple_two_sided_quote(hbt, stat.recorder)
  File "/Users/richardgriffiths/projects/hftbacktest/hftbacktest/proc/local.py", line 113, in submit_order
    raise KeyError('Duplicate order_id')
KeyError: 'Duplicate order_id'
```
[Archive.zip](https://github.com/nkaz001/hftbacktest/files/11183845/Archive.zip)

**Comment by nkaz001** [comment]
Sorry, I only tested some of my notebooks and notebooks in examples after the last update.

Firstly, it is important to note that HftBacktest takes order latencies into account, which means that cancel(and submit) requests are not processed immediately. The order request is only processed by the exchange after the order entry latency, and the local will acknowledge the order's status after the order response latency.

As you already figured out, you need to wait for the cancellation request to be processed and received by the local.

However, there is one tricky case to consider when attempting to cancel an order that has already been filled on the exchange side.

In this scenario, the cancel request will be ignored, and even after the local receives the cancel request's response (by using `wait_order_response` or `wait=True`), the filled order response may not yet have been received by the local, depending on the response latency. This means that the order could still look active on the local.

So, I recommend that you check for outstanding orders before submitting any new orders. Please refer to [the gridtraing example](https://github.com/nkaz001/hftbacktest/blob/master/examples/gridtrading_eth.ipynb).

Additionally, I have updated the `simple_two_sided_quote` to cancel all outstanding orders, wait for the response, and use non-duplicated order_ids.

**Comment by griffiri** [comment]
Thanks the `simple_two_sided_quote` example runs fine with the very small data set I am using and the explanation makes sense. Once I understand this example pretty well I'll take a look at the grid trading example.
