### ISSUE TITLE
Demo of arbitrage of bookTicker data across exchanges

### ISSUE THREAD

**Issue by ffssea** [nkaz001/hftbacktest#126]
Thank you so much for your amazing work. We are very interested in arbitrage bookTicker data across exchanges using the rust version of the code. Can you give us some runnable examples?

**Comment by ffssea** [comment]
Why does the error occur when I use depth for gridtrading backtesting.
![30ef572bfa47efa0b04ef6e881512fc](https://github.com/user-attachments/assets/cb711149-cf93-4ffe-ae59-7a33163ac39f)
![9ee1529e2ad9b6bbc821bfa0b6ad82a](https://github.com/user-attachments/assets/f334aacb-a5ad-4067-a926-0b955a0f3b43)

My data is as follows:
[ref_BTC_USDT-20240821.csv](https://github.com/user-attachments/files/16695194/ref_BTC_USDT-20240821.csv)

**Comment by nkaz001** [comment]
The issue you raised is that when elapse is invoked, it immediately jumps to the end of the data (`i64::MAX` timestamp), correct? I don’t have any problems with this. Which version are you using, and how are you inputting the feed data?"

Please see the attached file, which I saved as an npz file. You will need to decompress it once.
[BTCUSDT_20240821.npz.gz](https://github.com/user-attachments/files/16710617/BTCUSDT_20240821.npz.gz)

**Comment by ffssea** [comment]
Thanks for your reply.
When using the BTCUSDT_20240821.npz.gz you provided, the problem still exists. Is there an error in my data collection phase? Or is there a bug in the data conversion phase?
Here is the code I used, modified from your example. Looking forward to your reply.
[hft_demo1.zip](https://github.com/user-attachments/files/16711355/hft_demo1.zip)

**Comment by nkaz001** [comment]
Could you try again using the latest version `0.3.2`? There have been many changes, including updates to the data format.

**Comment by ffssea** [comment]
Now the example runs correctly. It would be very grateful if you could share your data processing code.

**Comment by nkaz001** [comment]
Sure.

```
import polars as pl
import numpy as np

df = (
    pl.read_csv('ref_BTC_USDT-20240821.csv', has_header=False)
    .with_columns(
        pl.col('column_1').cast(pl.UInt64).alias('ev'),
        pl.col('column_2').alias('exch_ts'),
        pl.col('column_3').alias('local_ts'),
        pl.col('column_4').alias('px'),
        pl.col('column_5').alias('qty'),
        pl.col('column_6').cast(pl.UInt64).alias('order_id'),
        pl.col('column_7').alias('ival'),
        pl.col('column_7').cast(pl.Float64).alias('fval')
    )
    .select(['ev', 'exch_ts', 'local_ts', 'px', 'qty', 'order_id', 'ival', 'fval'])
)
np.savez_compressed('BTCUSDT_20240821.npz', data=df.to_numpy(structured=True))
```

**Comment by ffssea** [comment]
Thanks for your help, this issue has been resolved. Looking forward to more communication.
