### ISSUE TITLE
In grid trading example, the best_ask price is always NaN

### ISSUE THREAD

**Issue by lli839** [nkaz001/hftbacktest#127]
I'm using 2.0.0 version.
Data: Use the BTCUSDC from https://github.com/nkaz001/hftbacktest/issues/69#issuecomment-2273239534

I'm testing the plain grid trading example: https://hftbacktest.readthedocs.io/en/latest/tutorials/High-Frequency%20Grid%20Trading.html

TickSize=0.1, LotSize=0.001.

The dataframe seems alright. However, after running the entire example, I notice the best_ask price is always NaN. So, no order is submitted.

Any reason?

**Comment by nkaz001** [comment]
Which date of BTCUSDT data is used?

**Comment by nkaz001** [comment]
Did you use `ROIVectorMarketDepthBacktest`? If so, could you check whether you set the correct `roi_lb` and `roi_ub` values? `roi_lb` is the lower bound of the market depth, and `roi_ub` is the upper bound.
