### ISSUE TITLE
Grid Trading + Support/Resistance

### ISSUE THREAD

**Issue by alohane** [nkaz001/hftbacktest#13]
I'm working on a project based on your research related to Grid Trading, but I added Support/Resistance to it to reduce the number of entries. Can I contact you via Telegram?

**Comment by nkaz001** [comment]
It's preferable to post your question here, but if you'd like to discuss privately, please find me at nkaz001#2359 on Discord.

**Comment by alohane** [comment]
please accept my friend request.
