### ISSUE TITLE
Calculate the average holding time of position

### ISSUE THREAD

**Issue by ffssea** [nkaz001/hftbacktest#133]
My code doesn't seem to be working as expected, how do I modify it or is this completely the wrong approach.

```
  let curr_orders = hbt.orders(0);

  let holding_ts = curr_orders
      .iter()
      .filter(|(_, x)| x.status == Status::Filled)
      .map(|(_, x)| hbt.current_timestamp() - x.local_timestamp)
      .sum::<i64>() as f64
      / curr_orders.len() as f64;
```

**Comment by nkaz001** [comment]
Wouldn't it be better to compute holding time based on position changes?

**Comment by ffssea** [comment]
Thanks for clearing up the confusion, this is a good way to calculate the holding time.
