### ISSUE TITLE
How to get historical market data during the backtesting process

### ISSUE THREAD

**Issue by loorr** [nkaz001/hftbacktest#156]
I want to obtain historical prices, trading volumes and other market data before the current time point during the backtesting process to help me post new orders or cancel orders at the current moment. How can I obtain historical market data during the backtesting process?

**Comment by nkaz001** [comment]
You'll need to store past values manually. For example, if you're working with time-series data for prices at specific intervals, you should record these values in an array or list. Here’s [an example](https://hftbacktest.readthedocs.io/en/py-v2.1.0/tutorials/Working%20with%20Market%20Depth%20and%20Trades.html#Rolling-Volume-Weighted-Average-Price) that might help.

**Comment by loorr** [comment]
您好，您的来信我已收到祝好~

**Comment by loorr** [comment]
Thanks for your help, this is very useful!
