### ISSUE TITLE
Abnormal Differences between reading single file v.s. reading chunked file

### ISSUE THREAD

**Issue by spacegoing** [nkaz001/hftbacktest#16]
Hi nkaz001,

Many thanks for this awesome project!

Quick question, my orderbook data is too large to fit in memory, therefore I need to chunk one single file to multiple chunked files.

The problem is that the result is different between reading a single file and reading multiple chunk files.

The way I test is that I first created a single file example `btcusdt_20230405.npz` using the file [btcusdt_20230405.dat.gz](https://github.com/nkaz001/hftbacktest/blob/master/examples/usdm/btcusdt_20230405.dat.gz) by `convert()` as documented. And then I split that file into 7 subfiles. I then running these two experiments by changing hbt's input like this:

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/5180020/234711579-3125b29a-e946-490f-965e-92f9bcbe4b15.png">
Left is reading chunked files, Right is reading single file.

However, the backtest results are different:
Single File Result:
<img width="375" alt="image" src="https://user-images.githubusercontent.com/5180020/234711887-396fa081-3fea-4d74-9f47-52fb678ff3c0.png">

Chunked File Result:
<img width="370" alt="image" src="https://user-images.githubusercontent.com/5180020/234711829-6df610b6-d98b-4e47-8eac-b77e36eb9f38.png">

One possible reason is that, I did some research and find it really weird that from the 1324th environment step (elapse step), the current_timestamp between chunked hbt and single hbt become different:
<img width="716" alt="image" src="https://user-images.githubusercontent.com/5180020/234712243-bb567718-3497-4124-a443-236ae067cb6a.png">

I double checked the underlying data, they are identical.

I have two questions:
1. Could you please think about the reason for this difference?
2. What is the best practice for loading huge orderbook dataset?

My email is spacegoing@gmail.com. I am more than happy to have a quick chat with you to help u replay this issue.

Many thanks!

**Comment by nkaz001** [comment]
Can you please inform me about the specific indexes used to divide the data so I try replicating the issue? Also, minor differences may happen if data is split and feed latency model is used due to the feed latency model's limitations; it cannot search the subsequent or preceding data chunks while attempting to find available feed latency. But, I'm not sure if this is the case.

**Comment by spacegoing** [comment]
Hi nkaz, many thanks for your reply!

I have uploaded my scripts and data here:
https://github.com/spacegoing/hbt/tree/master/examples

[btcusdt_20230404_eod.npz](https://github.com/spacegoing/hbt/blob/master/examples/btcusdt_20230404_eod.npz)
and [btcusdt_20230405.npz](https://github.com/spacegoing/hbt/blob/master/examples/btcusdt_20230405.npz) are generated from documentation scripts.

I then use [save_chunks_npz.py](https://github.com/spacegoing/hbt/blob/master/examples/save_chunks_npz.py) to save btcusdt_20230405.npz as 2MB large chunked files in the folder [test_chunks](https://github.com/spacegoing/hbt/tree/master/examples/test_chunks). I double checked that chunked files are identical to original file.

I then use [learn_pmm.py](https://github.com/spacegoing/hbt/blob/master/examples/learn_pmm.py) to test both single file and chunked file cases. And there are some test code under __main__.

Please let me know if there is anything else I can provide. Many thanks!
