### ISSUE TITLE
Missing data for examples

### ISSUE THREAD

**Issue by SimkoCarlos** [nkaz001/hftbacktest#162]
Hey!
Been looking into the examples and trying to replicated them locally but some of the data is not available on the repository. Can this be added ?

**Comment by nkaz001** [comment]
Some of the data used in the backtesting example originates from a third-party source. Due to licensing restrictions, I am unable to upload or share this raw data. You can find most of the data from Tardis.dev.

**Comment by SimkoCarlos** [comment]
Ok, thanks for the quick turn around
