### ISSUE TITLE
`clear_depth` inconsistent value

### ISSUE THREAD

**Issue by spacegoing** [nkaz001/hftbacktest#17]
Hi nkaz, please correct me if i'm wrong.

In current implementation, when clear_depth event hits, it clears "Clear the bid/ask market depth within the snapshot bid range."

However, the `clear up to price` is assigned as `ask's best price` and `bid's worst price` in the snapshot:
<img width="672" alt="image" src="https://user-images.githubusercontent.com/5180020/235254623-f78c8f82-025d-42ae-8604-9cb29c8e2c5c.png">
<img width="668" alt="image" src="https://user-images.githubusercontent.com/5180020/235254730-d687c3e6-e48a-4d32-a5a2-9b8513081137.png">

And in marketdepth implementation, it clears from `current best price` to `clear up to price`:
<img width="854" alt="image" src="https://user-images.githubusercontent.com/5180020/235255098-11ee20a5-d848-40f8-90a3-cdf37819c27b.png">

In this case, it clear's current best ask to snap best ask , while clears current best bid to snap worst bid. which leaves an inconsistency.

I have two questions:
1. May I ask why is clear event needed?
2. Shouldn't it always be current best to snap worst for both ask and bid?

many thanks!

**Comment by nkaz001** [comment]
Firstly, the Binance Futures snapshot feed collected by [collect-binancefutures](https://github.com/nkaz001/collect-binancefutures) is sorted from the best to the furthest. This is also the case for Tardis data, as confirmed by their sample file. Therefore, `bid_clear_upto` is the lowest bid in the snapshot and `ask_clear_upto` is the highest ask.

HftBacktest is primarily implemented based on Binance Futures feed even though it can be used for any exchange with proper data conversion. Occasionally, you may lose connection to the exchange or encounter a gap in update id. You can find more details about update id gap [here](https://binance-docs.github.io/apidocs/futures/en/#how-to-manage-a-local-order-book-correctly). So, it's essential to restore the market depth state, as only changes in market depth are sent.

However, the full market depth snapshot is not provided, with a maximum depth of 500 being offered. Clearing all levels would result in losing the full market depth view, necessitating the accumulation of market depth changes over time to fill beyond the 500-depth. Although the integrity of data beyond 500-depth isn't guaranteed, it's chosen to be retained to continuously maintain the full market depth. So, it needs to clear only a specific depth.
