### ISSUE TITLE
How to read csv in your snapshot and dataframe ?

### ISSUE THREAD

**Issue by mrunix1998** [nkaz001/hftbacktest#2]
Hi @nkaz001 
How can I use my csv tick_data from nasdaq indices into your jupyter-notebook for using strategy?
Thanks :)

**Comment by nkaz001** [comment]
Do you want to backtest trading nasdaq indices? If so, you cannot. This hft backtesting tool needs not only trade data but also full market-depth data or, at least, multi-level market-depth data. Even though you cannot use this tool, you can easily make your own backtester under particular assumptions.

*Assumptions*
* you can directly trade nasdaq indices
* the indices is the same as traded price in the same exchange you trade.
* no market impact / no fill in the queue

make your bid filled when the index is less than your bid(when the index is traded at less than your bid).
make your ask filled when the index is greater than your ask(when the index is traded at greater than your ask).

But be aware that those assumptions can be too strong to be applied.
