### ISSUE TITLE
Get error when using package built from source

### ISSUE THREAD

**Issue by quantitative-technologies** [nkaz001/hftbacktest#26]
I built `hftbacktest` from source with `python -m build`, and then installed it.

When I then tried the Getting Started notebook, I got the following error:

```console
ImportError: cannot import name 'randomdecl' from 'numba.core.typing' 
```

After uninstalling, and reinstalling using `pip install hftbacktest` the problem is gone.

I thought I should point this out.

**Comment by nkaz001** [comment]
Thank you for your report. If you attempted to build from the source, it is possible that the issue arises from version inconsistencies for numpy and numba.

**Comment by quantitative-technologies** [comment]
Welcome.

I think I understand what happened then: My numba version was 0.56.4 when I built from source, but gets upgraded to 0.57.1 when hftbacktest is installed. So I will close the issue if that's OK.
