### ISSUE TITLE
Normalize Binance futures orderbook data

### ISSUE THREAD

**Issue by quantitative-technologies** [nkaz001/hftbacktest#27]
I wanted to take advantage of the [freely available historical futures orderbook level 2 data from binance](https://github.com/binance/binance-public-data/tree/master/Futures_Order_Book_Download).

It should be possible by combining this with historical trade data (also available from binance I believe) to obtain normalized data for `htfbacktest`. 

But I couldn't find this in the repo examples. I wanted to check if it has already been done, so I don't waste time redoing it?

**Comment by nkaz001** [comment]
There isn't. If you provide an example file for me to look into its format, I would add an example converter.

**Comment by nkaz001** [comment]
By the way, without a local timestamp indicating when you received the feed, accurate backtesting is not possible, as there is no feed latency information. While you can artificially generate a local timestamp by assuming feed latency, it is preferable to collect the data yourself for more reliable results.

**Comment by quantitative-technologies** [comment]
> There isn't. If you provide an example file for me to look into its format, I would add an example converter.

Here is example LOB data for a single day: https://drive.google.com/file/d/1rVaDblmYJL0aPpgvdJ-fU9QFhMDga6f_/view?usp=sharing

Btw, I was also happy to write it, but wanted to make sure I wasn't "reinventing the wheel".

**Comment by quantitative-technologies** [comment]
Yes, good point about the local timestamp. Thanks for the tip.

The artificial local timestamps are fine for my purposes at the moment.

**Comment by quantitative-technologies** [comment]
Right. I was not suggesting trying to use OB data alone. Actually, I found your repo while looking for an implementation for inventory models, which of course need trade data to fit them.

The trade data is available from the [Binance Public Data](https://github.com/binance/binance-public-data):

```console
wget https://data.binance.vision/data/futures/um/daily/trades/BTCUSDT/BTCUSDT-trades-2020-07-01.zip
```
Here is the [trade data](https://drive.google.com/file/d/1eZ7Ze0lsU2hiyNC9K_KZIaBjegafeKrv/view?usp=sharing) corresponding to the above depth data.

**Comment by nkaz001** [comment]
I added the converter. [hftbacktest/data/utils/binancehistmktdata.py](https://github.com/nkaz001/hftbacktest/blob/master/hftbacktest/data/utils/binancehistmktdata.py)

could you check if it works as expected? again, in my experience, I have observed that backtest results can exhibit significant discrepancies unless precise feed latency and order latency are used.

**Comment by quantitative-technologies** [comment]
Excellent!

My plan was to look into the inventory MM model (as you gave an example of). I will report it if anything unexpected shows up.

I think you mean significant discrepancies between backtest and live trading results, but I am not doing any live trading at the moment. If you want to me to try out one of your other examples with the binance historical data, please let me know.

**Comment by nkaz001** [comment]
Thanks for the report. Please see the latest commit. 740feee413795ea2a196077926e5def9e123229b

**Comment by quantitative-technologies** [comment]
Thanks for updating the code.

Now I can successfully run the data preparation notebook. 

However, when I use the prepared data from binance in the Guéant–Lehalle–Fernandez-Tapia Market Making Model and Grid Trading notebook, it is off by a factor of about 2 in trading intensity from your calculated results. For example:
![hftbacktest_fit_2023-08-15_14-49-17](https://github.com/nkaz001/hftbacktest/assets/29150871/0a649267-8b1d-4819-86f9-66694f31a41f)

It's as if there are only half as many trades in the data files obtained from binance. To be safe, I added a 10ms feed latency, but as expected that does not affect the fitted model parameters.

Note that I had to adjust for the fact that the binance data is timestamped to milliseconds rather than microseconds.

Would it be possible to share your collected data for ETHUSDT futures on 2022-10-03 (e.g. on Google drive)? That way people could reproduce your results, and also I could directly compare the trade data to binance.

**Comment by nkaz001** [comment]
For your information, I used `trade` stream instead of `aggTrade` stream which is currently officially documented but aggregated.

**Comment by quantitative-technologies** [comment]
I'm not sure I understand, since I also used `trade` data from binance, rather than `aggTrade`. In fact, your converter does not even work on the binance historical `aggTrade` data, though I don't see a need for it. 

Unless you are suggesting that the `trade` data from binance is in fact still aggregated?

Anyhow, my plan is to collect my own data from the stream and then I can compare with the historical data from binance.

**Comment by nkaz001** [comment]
No. But `trade` stream functions as expected, just like its description in the official spot API document, even though it is not outlined in the official futures API documents. So I guess Binance's historical data also came from `aggTrade`. Comparison is the most effective way for figuring things out.

**Comment by quantitative-technologies** [comment]
Another issue showed up: I was working with more recent data, and it has an additional undocumented field `trans_id`. This changes the offset of the other fields, and breaks the converter. 

Here is an example of the recent snapshot data: https://drive.google.com/file/d/1y-9nt9V-eB_OV3uSq4-dzBe-eOsQDt4S/view?usp=sharing

**Comment by nkaz001** [comment]
See 2b3137c3c643e9a96621e8fb0c3cd46ab0922dde and let me know if it works as expected.

**Comment by quantitative-technologies** [comment]
Code looks much better now without hard-coded indices, and it processes the snapshot fine.

But now it fails on the `convert` function call in the validation step with an exception.

Here is the [lob data](https://drive.google.com/file/d/1X46yMgNarKp6NR2WDIsNZeZ7wrfIKAtb/view?usp=sharing) and [trade data](https://drive.google.com/file/d/1tM39EYFsuXWpTGfv8HL8ODTbqG_z40cr/view?usp=sharing) to reproduce this.

**Comment by quantitative-technologies** [comment]
Thanks! I tested it out and there were no more errors.

I'm not sure exactly what discrepancy you mean, but perhaps it will become more clear as I continue working on it.

**Comment by nkaz001** [comment]
What I meant by that is that any difference from the live trading environment can cause a discrepancy.

**Comment by phybrain** [comment]
> Thanks for updating the code.
> 
> Now I can successfully run the data preparation notebook.
> 
> However, when I use the prepared data from binance in the Guéant–Lehalle–Fernandez-Tapia Market Making Model and Grid Trading notebook, it is off by a factor of about 2 in trading intensity from your calculated results. For example: ![hftbacktest_fit_2023-08-15_14-49-17](https://private-user-images.githubusercontent.com/29150871/260769828-0a649267-8b1d-4819-86f9-66694f31a41f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NTcxMDAsIm5iZiI6MTcwMTc1NjgwMCwicGF0aCI6Ii8yOTE1MDg3MS8yNjA3Njk4MjgtMGE2NDkyNjctOGIxZC00ODE5LTg2ZjktNjY2OTRmMzFhNDFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA2MTMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiNjZlMWJiYzczMGNhYTQxNjZkZGU4YTdiZTlkZTYxYmI0OTI3ZTBiOGYyNzZkNDlkMDI0YTE0NDI2YWEzNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FKgF2mly4pNEVvh-Ih8ksIergKUS6H0hffpb9-KZllk)
> 
> It's as if there are only half as many trades in the data files obtained from binance. To be safe, I added a 10ms feed latency, but as expected that does not affect the fitted model parameters.
> 
> Note that I had to adjust for the fact that the binance data is timestamped to milliseconds rather than microseconds.
> 
> Would it be possible to share your collected data for ETHUSDT futures on 2022-10-03 (e.g. on Google drive)? That way people could reproduce your results, and also I could directly compare the trade data to binance.

Could you provide the code of Guéant–Lehalle–Fernandez-Tapia Market Making Model?   ：）

**Comment by nkaz001** [comment]
you can find it on [tutorials page](https://hftbacktest.readthedocs.io/en/latest/index.html) or [examples](https://github.com/nkaz001/hftbacktest/tree/master/examples) directory.

**Comment by phybrain** [comment]
> you can find it on [tutorials page](https://hftbacktest.readthedocs.io/en/latest/index.html) or [examples](https://github.com/nkaz001/hftbacktest/tree/master/examples) directory.

thanks
