### ISSUE TITLE
Question on Queue Model's is_filled function

### ISSUE THREAD

**Issue by AndersonatAMC** [nkaz001/hftbacktest#3]
The function definition is:

`
def is_filled(self, order, hbt):
        return round(order.q[0] / hbt.lot_size) < 0
`

Why the left side must be smaller than 0? "<=" should work

**Comment by nkaz001** [comment]
Doesn't that("=") mean the order is at the frontmost of the queue as order.q[0] is qty ahead of the order?

**Comment by AndersonatAMC** [comment]
I see what you mean, yes you're right.
