### ISSUE TITLE
Unclear snapshot requirement for Tardis data

### ISSUE THREAD

**Issue by degloff** [nkaz001/hftbacktest#34]
Tardis incremental_book_l2_*.csv.gz files contain a snapshot at the very beginning of each file. 

In the [doc](https://hftbacktest.readthedocs.io/en/latest/tutorials/Data%20Preparation.html#Creating-a-market-depth-snapshot) it is nicely explained how to create a snapshot EOD, which is then passed to the backtest function.

I assume that this is not required for Tardis data, however it is not clear as the [doc](https://hftbacktest.readthedocs.io/en/latest/tutorials/Data%20Preparation.html#Getting-started-from-Tardis.dev-data) also says:

> You can also build the snapshot in the same way as described above.

Can you clarify if this is needed. I also checked the code and it seems not needed.
Thanks for clarifying this, and eventually update the doc. If it is needed we might need a function to extract the beginning of day snapshot from a Tardis incremental_book_l2 file?

**Comment by nkaz001** [comment]
I don't actively use Tardis data. I wasn't aware that Tardis data contains a snapshot at the beginning of each daily file. Could you please confirm if Tardis data always includes a complete SOD snapshot?

**Comment by degloff** [comment]
Actually the documentation confirms this [here](https://docs.tardis.dev/historical-data-details#collected-order-book-data-details) and [here](https://docs.tardis.dev/faq/data#how-can-i-reconstruct-full-order-book-state-from-incremental_book_l2-csv-dataset). I can also confirm as I checked it on the data. Hope that helps.

**Comment by nkaz001** [comment]
Thank you for the confirmation. However, I'm still wondering if it's a complete snapshot. Based on my understanding of the document, it fetches a snapshot from an exchange. But in the case of Binance, they don't provide a complete snapshot through their API. Therefore, to maintain a complete snapshot, one still needs to build upon the previous state, even if the fetched snapshot is applied.

**Comment by degloff** [comment]
You are indeed right. It is a snapshot taken SOD. It is not a full book but as good as you can be when you connect at that moment. But the previous state just contains the EOD of last day. You would need to run through the full history to get all the levels and assume there was no disconnect. Having SOD snapshots of 1000 levels is probably good from a practical perspective.

**Comment by nkaz001** [comment]
Roughly 1000 levels on each side equates to about $100 in the case of BTCUSDT. This can be more, as there may be empty levels, but it's only about 0.3% from the midpoint.

So, I think it's essential to preserve the full depth of the market from the previous state, even if there is discrepancies with the actual order book. 

Since there's no way to obtain the full depth of the market, it's the best bet. That's the reason why hftbacktest only clears the depth in the snapshot and maintains the order book behind the snapshot and also you need to input the initial snapshot.

**Comment by nkaz001** [comment]
I added `snapshot_mode` argument. This allows you to bypass the SOD snapshot of Tardis data and exclusively use the snapshot provided to `hftbacktest`, which contains a full depth of market snapshot and also can be created by the hftbacktest data utility. Given that the Binance market depth stream is aggregated and occasionally misses data, I believe it would be acceptable to ignore all snapshot events in Tardis data. Over time, the order book will converge to a complete order book.
