### ISSUE TITLE
Gather data for multiple days

### ISSUE THREAD

**Issue by pepi99** [nkaz001/hftbacktest#40]
I checked out the library you have linked (https://github.com/nkaz001/collect-binancefutures), but it seems that it is gathering data live. 

Regarding Tardis, they allow to get the data for the first day of each month, which is not enough for a meaningful backtest. 

I see in your documentation you have data for multiple days, how did you get it?

Regards

**Comment by nkaz001** [comment]
I usually collect data myself or purchase it from a vendor; recently, I opted to purchase it, but it varies depending on my budget.
