### ISSUE TITLE
Loading With Snapshots and Trade Data Only

### ISSUE THREAD

**Issue by R-K-H** [nkaz001/hftbacktest#42]
Hello,

I have some data which is trades data, and full order snapshots only. I've created a import and digest strategy based off of Tardis and BinanceFutures import regime.

Will the backtest function without DEPTH_EVENTs eg I only have DEPTH_CLEAR_EVENT, DEPTH_SNAPSHOT_EVENT and TRADE_EVENT? Or am I barking up a wrong tree here?

Everything seems to load in and the data structure and aggregation match what appears to be the desired output and example functions run, but what the backtester sees and what the data is aren't congruent.

Trades:
<img width="612" alt="Screenshot 2023-09-27 at 10 02 15 AM" src="https://github.com/nkaz001/hftbacktest/assets/1007667/f6b39c54-b317-4007-bd40-3d9b9a047ea7">

Snapshot of 5 levels (which are consumed and produced into multiple rows with same execution timestamp and DEPTH_CLEAR_EVENT before DEPTH_SNAPSHOT_EVENT)
<img width="834" alt="Screenshot 2023-09-27 at 10 02 23 AM" src="https://github.com/nkaz001/hftbacktest/assets/1007667/c00d5217-16e7-45b0-8660-34d994b436a6">

When digested and combined the resulting dataset:
<img width="962" alt="Screenshot 2023-09-27 at 10 16 56 AM" src="https://github.com/nkaz001/hftbacktest/assets/1007667/b72d7bfd-7b4d-4257-82cd-cecdbe4bacac">

Example output from the data aggregation (and following the Data Preparation workbook)
```
data = create_last_snapshot(f"{DATA_FOLDER}{EXPORT_FILE_NAME}", tick_size=TICK_SIZE, lot_size=LOT_SIZE)
# Create snapshot for end of day.
np.savez(f"{DATA_FOLDER}{EXPORT_SNAPSHOT_FILE_NAME}", data=data)
data
array([[ 4.0000000e+00,  1.6833258e+15, -1.0000000e+00,  1.0000000e+00,
         2.0612000e+03,  1.0000000e+00],
       [ 4.0000000e+00,  1.6833258e+15, -1.0000000e+00,  1.0000000e+00,
         2.0611000e+03,  9.0000000e+00],
       [ 4.0000000e+00,  1.6833258e+15, -1.0000000e+00,  1.0000000e+00,
         2.0610000e+03,  8.0000000e+00],
       ...,
       [ 4.0000000e+00,  1.6833258e+15, -1.0000000e+00, -1.0000000e+00,
         2.0615000e+03,  1.5000000e+01],
       [ 4.0000000e+00,  1.6833258e+15, -1.0000000e+00, -1.0000000e+00,
         2.0616000e+03,  6.0000000e+00],
       [ 4.0000000e+00,  1.6833258e+15, -1.0000000e+00, -1.0000000e+00,
         2.0617000e+03,  1.1000000e+01]])
```

Happy to provide more details and additional information, just wondering where I might start (as the only key difference is the lack of DEPTH_EVENTs when comparing the two datasets).

**Comment by R-K-H** [comment]
I removed the DEPTH_CLEAR_EVENT from the construction of the data set with only the DEPTH_SNAPSHOT_EVENT within the data set and it seems to have resolved the issue.

<img width="810" alt="Screenshot 2023-09-27 at 11 39 36 AM" src="https://github.com/nkaz001/hftbacktest/assets/1007667/63105f79-69c8-4ab6-8eb0-d95674e33366">

Still need to resolve the strategy issue where it's not behaving, but at least the data the backtester seems to understand is aligned with the dataset.

**Comment by R-K-H** [comment]
So I'm still having issues with either my lot size or tick size (loading say GBPUSD futures or XAUUSD futures) does the codebase infer any particular structure for crypto specifically or should I be thinking about this a different way? The lot size's for the futures are say 1.0 as the min order amount and the price on the GBPUSD is 1.2312, but that's not REALLY the value of the lot as it's like 100 lots in one contract.

Is there a way to adjust for this or should I be approaching the problem differently?

**Comment by nkaz001** [comment]
Optimal practice involves having access to changes in market depth, but if you only possess a snapshot of market depth, it's advisable to transform it into changes in market depth. For instance, consider a snapshot with the following data:

Ask
100 @ 1500
150 @ 1490
Bid
100 @ 1480
200 @ 1470

In the subsequent snapshot:

Ask
100 @ 1500
Bid
100 @ 1490
100 @ 1480

You can perform the conversion as follows:

Delete Ask 150 @ 1490
Add Bid 100 @ 1490

You may choose to retain or delete Bid 200 @ 1470 at your discretion. This conversion facilitates the use of hftbacktest.

**Comment by R-K-H** [comment]
For reference specs: 
https://www.cmegroup.com/markets/fx/g10/british-pound.contractSpecs.html

If you need larger or want more formatted (Pandas/Numpy/Parquet) data, let me know (I did create a wrapper function which consumes and structures this into what HFTBacktest wanted (events, sides, etc.)

Trades
```
pyarrow.Table
side: string
price: double
quantity: double
transact_time: timestamp[us]
market: dictionary<values=string, indices=int32, ordered=0>
market_trade_id: string
----
side: [["B","O","B","O","O",...,"B","B","B","O","B"]]
price: [[1.2497000000000003,1.2498000000000002,1.2498000000000002,1.2499000000000002,1.2499000000000002,...,1.249,1.249,1.249,1.249,1.2489000000000001]]
quantity: [[1,9,1,1,1,...,1,4,11,2,7]]
transact_time: [[2023-05-02 00:00:04.533000,2023-05-02 00:00:13.450000,2023-05-02 00:00:16.477000,2023-05-02 00:00:31.618000,2023-05-02 00:00:31.719000,...,2023-05-02 23:53:45.662000,2023-05-02 23:53:45.662000,2023-05-02 23:53:45.662000,2023-05-02 23:54:29.214000,2023-05-02 23:55:02.034000]]
market: [  -- dictionary:
["CME"]  -- indices:
[0,0,0,0,0,...,0,0,0,0,0]]
market_trade_id: [["012dq33x9m2n9","012dq33x9m37h","012dq33x9m3hi","012dq33x9m4hu","012dq33x9m4hz",...,"012dq33xdat2i","012dq33xdat2i","012dq33xdat2i","012dq33xdatii","012dq33xdatuy"]]
```

L5 Order Book Snapshots:
```
pyarrow.Table
market: dictionary<values=string, indices=int32, ordered=0>
bid_price_0: double
offer_price_0: double
bid_quantity_0: double
offer_quantity_0: double
bid_price_1: double
offer_price_1: double
bid_quantity_1: double
offer_quantity_1: double
bid_price_2: double
offer_price_2: double
bid_quantity_2: double
offer_quantity_2: double
bid_price_3: double
offer_price_3: double
bid_quantity_3: double
offer_quantity_3: double
bid_price_4: double
offer_price_4: double
bid_quantity_4: double
offer_quantity_4: double
transact_time: timestamp[us]
----
market: [  -- dictionary:
["CME"]  -- indices:
[0,0,0,0,0,...,0,0,0,0,0]]
bid_price_0: [[1.2497000000000003,1.2497000000000003,1.2497000000000003,1.2497000000000003,1.2497000000000003,...,1.249,1.249,1.249,1.249,1.249],[1.249,1.249,1.249,1.249,1.249,...,1.2489000000000001,1.2489000000000001,1.2489000000000001,1.2489000000000001,1.2489000000000001]]
offer_price_0: [[1.2498000000000002,1.2498000000000002,1.2498000000000002,1.2498000000000002,1.2498000000000002,...,1.2491,1.2491,1.2491,1.2491,1.2491],[1.2491,1.2491,1.2491,1.2491,1.2491,...,1.249,1.249,1.249,1.249,1.249]]
bid_quantity_0: [[12,8,8,8,8,...,27,19,17,17,17],[17,17,17,17,17,...,4,3,3,3,3]]
offer_quantity_0: [[13,16,21,21,21,...,6,6,17,17,17],[17,17,17,17,20,...,10,10,18,10,10]]
bid_price_1: [[1.2496000000000003,1.2496000000000003,1.2496000000000003,1.2496000000000003,1.2496000000000003,...,1.2489000000000001,1.2489000000000001,1.2489000000000001,1.2489000000000001,1.2489000000000001],[1.2489000000000001,1.2489000000000001,1.2489000000000001,1.2489000000000001,1.2489000000000001,...,1.2488000000000001,1.2488000000000001,1.2488000000000001,1.2488000000000001,1.2488000000000001]]
offer_price_1: [[1.2499000000000002,1.2499000000000002,1.2499000000000002,1.2499000000000002,1.2499000000000002,...,1.2492000000000003,1.2492000000000003,1.2492000000000003,1.2492000000000003,1.2492000000000003],[1.2492000000000003,1.2492000000000003,1.2492000000000003,1.2492000000000003,1.2492000000000003,...,1.2491,1.2491,1.2491,1.2491,1.2491]]
bid_quantity_1: [[34,34,34,34,34,...,38,38,38,38,38],[38,38,38,38,38,...,25,25,25,25,25]]
offer_quantity_1: [[31,31,31,31,31,...,44,44,52,44,44],[44,52,52,52,52,...,29,29,29,29,29]]
bid_price_2: [[1.2495000000000003,1.2495000000000003,1.2495000000000003,1.2495000000000003,1.2495000000000003,...,1.2488000000000001,1.2488000000000001,1.2488000000000001,1.2488000000000001,1.2488000000000001],[1.2488000000000001,1.2488000000000001,1.2488000000000001,1.2488000000000001,1.2488000000000001,...,1.2487000000000001,1.2487000000000001,1.2487000000000001,1.2487000000000001,1.2487000000000001]]
```

**Comment by R-K-H** [comment]
> I've reviewed the CME document, and currently, I believe the best way to handle CME data is to convert it from Market-By-Order data to Market-By-Price data, which `hftbacktest` can then process.
> 
> Ultimately, it's the best to process MBO directly.
> 
> But, if you only have snapshot data, as I mentioned before, we'll need to convert that snapshot data to Market-By-Price data. This isn't ideal because it doesn't provide the full depth of market data.
> 
> Regardless, if you can provide sample data, I can create a converter for it. I'm uncertain about the optimal input format to cover different exchanges, but, CSV would be fine.

Sure thing, I'll see what I can do to get a small time interval set and I'll submit it within a PR. I've got our own system for data collection, so I'll submit a trades and snapshots csv to the PR.

I'll submit an ETH ETF and the GBPUSD so you can see what's what there. The big question beyond this is the quote size is whole integers, but the actual $ representation is like 100 contracts so big money vs an order of like 1 @ 1.2312 as the backtest may assume.

**Comment by nkaz001** [comment]
Regarding the quote size, can it be handled by `contract_size` in `LinearAsset` or by implementing `assettype`?

**Comment by R-K-H** [comment]
> Regarding the quote size, can it be handled by `contract_size` in `LinearAsset` or by implementing `assettype`?

It could, I'm not sure I've read through the documentation on creation of assettype so I'll have to dig through that. I apologize not fully familiar with the entire system.

**Comment by nkaz001** [comment]
no worries. feel free to ask if you have a question.

**Comment by nkaz001** [comment]
Please see the following example for converting the order book snapshot feed data into market-by-price feed data. But, be aware that the queue position of orders placed outside of the order book could be incorrect, leading to completely wrong results in fill simulation.

```
from hftbacktest.data.utils.difforderbooksnapshot import DiffOrderBookSnapshot

data = pq.read_table(f"{DATA_FOLDER}{QUOTES_FILE_NAME}")
if data is not None:
    df = data.to_pandas()
    rows = np.zeros((df.size * 10, 6), np.float64)
    
    diff_ob = DiffOrderBookSnapshot(5)
    
    rn = 0
    for timestamp, row in df.iterrows():
        diff_ob.begin_update()
        for i in range(5):
            diff_ob.update_bid(row[f'bid_price_{i}'], row[f'bid_quantity_{i}'])
            diff_ob.update_ask(row[f'offer_price_{i}'], row[f'offer_quantity_{i}'])
        bids, asks, bid_dels, ask_dels = diff_ob.done_update()
        
        exch_timestamp_us = timestamp.timestamp() * 1_000_000
        base_latency = 100
        local_timestamp_us = timestamp_us + base_latency
        
        for item in bids:
            if item[2] == 1:
                rows[rn] = [DEPTH_EVENT, exch_timestamp_us, local_timestamp_us, 1, item[0], item[1]]
                rn += 1
        for item in asks:
            if item[2] == 1:
                rows[rn] = [DEPTH_EVENT, exch_timestamp_us, local_timestamp_us, -1, item[0], item[1]]
                rn += 1
        for item in bid_dels:
            rows[rn] = [DEPTH_EVENT, exch_timestamp_us, local_timestamp_us, 1, item[0], 0]
            rn += 1
        for item in ask_dels:
            rows[rn] = [DEPTH_EVENT, exch_timestamp_us, local_timestamp_us, -1, item[0], 0]
            rn += 1
    
    rows = rows[:rn]
```
