### ISSUE TITLE
Moving from hftbacktest to live

### ISSUE THREAD

**Issue by volemont** [nkaz001/hftbacktest#47]
Thanks for this great project.

How would you move from backtesting to live without having to re-implement the strategy logic and introduce bugs in the process?

For example, ideally [def market_making_algo(hbt)](https://github.com/nkaz001/hftbacktest/blob/master/examples/example.py) could be used in [sample-trading-bot](https://github.com/nkaz001/sample-trading-bot).

**Comment by szad670401** [comment]
Same issue

**Comment by nkaz001** [comment]
Unfortunately, owing to the constraints imposed by Numba, I'm uncertain whether it's feasible to seamlessly transition the backtesting code into a live bot without some necessary modifications. Even if we were to eliminate the use of `numba.njit`, some adjustments might still be required, as the backtesting code currently lacks compatibility with any form of asynchronous operations.

I'll try to figure out what options could be feasible.

**Comment by nkaz001** [comment]
It's still at the very early stage of development, I updated Rust implementation that supports a live bot, currently Binance futures only. feedback and contributions are welcome. https://github.com/nkaz001/hftbacktest/tree/experimental_rust
