### ISSUE TITLE
Inactive orders

### ISSUE THREAD

**Issue by pepi99** [nkaz001/hftbacktest#53]
After each hbt.elapse(micros), all hanging orders are marked as inactive and can be removed using hbt.clear_inactive_orders(), right? 

I just want to make sure that the elapsing marks orders as inactive because it is intuitive, but I cannot find the part of code that does it.

**Comment by nkaz001** [comment]
Orders whose status is `CANCELED`, `FILLED`, `EXPIRED`, or `REJECTED` are considered inactive orders, while orders that have not been accepted yet are not considered inactive orders(status is `NONE`).
