### ISSUE TITLE
Converting tardis data results in error

### ISSUE THREAD

**Issue by pepi99** [nkaz001/hftbacktest#56]
```
date = '2023-08-08'

pair = 'ltc_usdt'
tick_size = tick_and_lot[pair]['tick_size']
lot_size = tick_and_lot[pair]['lot_size']

path = f'data/{pair.split("_")[0]}_tardis_npzs/{pair.replace("_", "")}_{date}_tardis.npz'

# Convert automatically cals validate data no need for us to do so
tardis.convert(["/".join(path.split("/")[:-1]) + "/tmp_ob.csv.gz","/".join(path.split("/")[:-1]) + "/tmp_trades.csv.gz"], output_filename=path)

```

Error:

```
    156 ss_ask = ss_ask[:ss_ask_rn]
    157 # Clear the ask market depth within the snapshot ask range.
    158 tmp[row_num] = [
    159     DEPTH_CLEAR_EVENT,
--> 160     ss_ask[0, 1],
    161     ss_ask[0, 2],
    162     -1,
    163     ss_ask[-1, 4],
    164     0
    165 ]
    166 row_num += 1
    167 # Add DEPTH_SNAPSHOT_EVENT for the ask snapshot

IndexError: index 0 is out of bounds for axis 0 with size 0

```

in file tardis.py

Here is a screenshot from the Debugger (when the ss_ask is empty):

<img width="834" alt="image" src="https://github.com/nkaz001/hftbacktest/assets/45050191/e03ca6b5-abc1-4b4f-9ef3-48d7f40a5cd6">

Maybe a useful note will be that the timestamp and local_timestamp sometime may be a bit shifted wrt what tardis gives (at maximum - one microsecond (sometimes)).

**Comment by nkaz001** [comment]
Could you please check if [this fix](https://github.com/nkaz001/hftbacktest/tree/fix_datautils) resolves the issue? It would be even better if you could verify whether the snapshot is indeed provided only for one side.
Additionally, could you provide more details regarding the local_timestamp issue?

**Comment by pepi99** [comment]
I have three snapshot events (for both sides) at times:

2023-08-08 00:00:00.023, 2023-08-08 05:31:00.545 and 2023-08-08 12:00:02.582 , (I get 1001 values per side per timestamp).

With the solution that you provided now - it works. Thank you very much. 

Regarding the timestamp issue, it comes due to some pandas conversions (since it doesn't have microsecond support iirc), mapping to and from datetime objects sometimes causes a discrepancy in the magnitude of a microsecond (at max). It is totally from my side.

Thanks again!

**Comment by pepi99** [comment]
Should this fix be merged to the master branch?

**Comment by bohblue2** [comment]
@pepi99  By any chance, can you tell me what this means IIRC?

**Comment by pepi99** [comment]
iirc = if I remember correctly

**Comment by nkaz001** [comment]
Sure. It has been merged. Thanks for checks up.
