### ISSUE TITLE
Potential speed-up for stat.equity

### ISSUE THREAD

**Issue by pepi99** [nkaz001/hftbacktest#58]
I have noticed that stat.equity() runs very slow. And it is used in your "sharpe", "sortino", "drawdown", "annualised_return" and "summary". When working in a sub-second intervals, this can run very slow because of many data points. 

A simple njit equity function runs 100x faster:

```
@njit
def equity(positions, mids, balances, fees):
    result = List()
    for i in range(len(positions)):
        result.append(positions[i] * mids[i] + balances[i] - fees[i])
    return result
```

```
s = time.time()
equities = equity(stat.position, stat.mid, stat.balance, stat.fee)
e = time.time()

print(f'Fast computation took: {e - s}')

s = time.time()
stat.equity()
e = time.time()

print(f'Stat computation took: {e - s}')

```

Output:
```
Fast computation took: 0.11081385612487793
Stat computation took: 11.64174509048462

```
(2 million elements)

I have not looked deep into your code to find why exactly the equity function runs slow, I suppose it's because of pandas.

**Comment by nkaz001** [comment]
`Stat.equity` converts the timestamp to DateTime as the index of the returned Pandas Series. Converting the timestamp takes some time. If you need to obtain equity without datetime conversion, I will add an option for it.

**Comment by pepi99** [comment]
Personally, I can work with the above function. Just didn't notice that pandas timestamp conversion was slow and that it is needed for the plots. Thanks
