### ISSUE TITLE
Problem with some Tardis data

### ISSUE THREAD

**Issue by artiko88** [nkaz001/hftbacktest#62]
Hey!

I am having problems converting data from Tardis for following assets/days:

```
Reading data/binance-futures/SOLUSDT/_trades_2024-01-09_SOLUSDT.csv.gz
Reading data/binance-futures/SOLUSDT/_incremental_book_L2_2024-01-09_SOLUSDT.csv.gz
Error occurred during conversion: index 1500 is out of bounds for axis 0 with size 1500

Reading data/binance-futures/TRBUSDT/_trades_2023-12-31_TRBUSDT.csv.gz
Reading data/binance-futures/TRBUSDT/_incremental_book_L2_2023-12-31_TRBUSDT.csv.gz
Error occurred during conversion: index 1500 is out of bounds for axis 0 with size 1500
```

I get the sam error on both dates:
_Error occurred during conversion: index 1500 is out of bounds for axis 0 with size 1500_

Which seem very strange to get the same kind of error on two different asset/date combinations. 

P.S. Please, let me know if data upload somewhere on is necessary for debugging.

**Comment by nkaz001** [comment]
Please provide the data for the investigation.

**Comment by artiko88** [comment]
Here's the data.

[You can download it from here.](https://drive.google.com/drive/folders/16PV2zI4aSJ2Ty7NJddTBcgoL7kfOfiGz?usp=sharing)

**Comment by artiko88** [comment]
Both SOL and TRB converted nicely. TRB required larger buffer size (i indeed used 1500) and SOL went nicely through the converter after applying the fix you kindly provided.

Thank you once again!
