### ISSUE TITLE
Converting Binance Public Data(or other external data) to hftbacktest's dataformat

### ISSUE THREAD

**Issue by objectin** [nkaz001/hftbacktest#7]
I want to backtest in a wide range of time series, so I need to use Binance's open public data(https://github.com/binance/binance-public-data). However, I am not sure about the exact data structure in hftbacktest. Can you provide guidelines or an example code for importing external data?

**Comment by nkaz001** [comment]
Could you check https://github.com/nkaz001/hftbacktest/wiki/Data and, if you have any further questions, provide additional details when asking again?
