### ISSUE TITLE
please add more exchanges like Bybit

### ISSUE THREAD

**Issue by SUSHANTH009** [nkaz001/hftbacktest#72]
suggestion for adding more exchanges

**Comment by nkaz001** [comment]
I'll add it to my list. But, the Rust live bot is still in the early stages of development, and there are many implementations to be made for its future development. Therefore, implementing another exchange besides Binance will take some time.

**Comment by nkaz001** [comment]
Bybit is a WIP.

**Comment by nkaz001** [comment]
@SUSHANTH009 hftbacktest rust v0.2.0 has been released with MVP Bybit connector.
