### ISSUE TITLE
'assets.json' in Making Multiple Markets

### ISSUE THREAD

**Issue by chihyanghsu** [nkaz001/hftbacktest#73]
Hi,
Thanks for providing this great project. Currently, I'm trying the "Making Multiple Markets" example. Could you kindly share the format or the example of 'assets.json' file to speed up my testing?

Thanks a lot.

**Comment by nkaz001** [comment]
Sure. It's a dictionary where the key is the symbol, and the value is another dictionary containing the tick size and lot size. See the following example.
{"1000shibusdt": {"tick_size": 1e-06, "lot_size": 1}, "eosusdt": {"tick_size": 0.001, "lot_size": 0.1}, ...}

**Comment by chihyanghsu** [comment]
Thanks for your help.
