### ISSUE TITLE
I try to use restful api to get depth-1000 data every 8 hours, but failed occasionally

### ISSUE THREAD

**Issue by LJingnan** [nkaz001/hftbacktest#79]
The error is as follow:
```
WARNING:root:Mismatch on the book. prev_update_id=4630306859680, pu=4630306859680
INFO:root:sending req to https://fapi.binance.com/fapi/v1/depth?symbol=ethusdt&limit=1000&timestamp=1716047999069: "symbol=ethusdt&limit=1000&timestamp=1716047999069"
WARNING:root:Mismatch on the book. prev_update_id=4630306859793, pu=4630306859793
WARNING:root:Mismatch on the book. prev_update_id=4630306862349, pu=4630306862349
INFO:root:sending req to https://fapi.binance.com/fapi/v1/depth?symbol=btcusdc&limit=1000&timestamp=1716047999171: "symbol=btcusdc&limit=1000&timestamp=1716047999171"
INFO:root:sending req to https://fapi.binance.com/fapi/v1/depth?symbol=btcusdt&limit=1000&timestamp=1716047999173: "symbol=btcusdt&limit=1000&timestamp=1716047999173"
WARNING:root:The book is initialized. symbol=ethusdt, prev_update_id=4630307007357
WARNING:root:The book is initialized. symbol=btcusdc, prev_update_id=4630307009982
正在 __keep_alive
WARNING:root:Timed out on request: /v1/depth ("symbol=btcusdt&limit=1000&timestamp=1716047999173"), retrying...
INFO:root:sending req to https://fapi.binance.com/fapi/v1/depth?timestamp=1716048006162: "timestamp=1716048006162"
ERROR:root:Unhandled Error: 400, message='Bad Request', url=URL('https://fapi.binance.com/fapi/v1/depth?timestamp=1716048006162'): Bad Request
ERROR:root:Endpoint was: GET /v1/depth: "timestamp=1716048006162"
```
It seems that it is a internet error, but It happens occasionally and unpredictably, which cause my program failed and stop. Do you have any idea to solve this problem. Thank you.

**Comment by nkaz001** [comment]
Are you referring to the Python version of collect-binancefutures? If so, please use the collect-binancefutures issue tracker.

Sometimes update id gaps occur repeatedly in the short term, so it may be better to maintain the order book based solely on the diff. depth stream. Retrying to recover by fetching a snapshot delays order book reconstruction and is also limited by API rate limits. The Rust version of collect-binancefutures removes that part and will be provided as an option.

**Comment by LJingnan** [comment]
Yes I am using the python api. Sorry I should put this in collect-binancefutures issue tracker. 
"The Rust version of collect-binancefutures removes that part", do you mean that rust version would not try to recover by fetching a snapshot and just stop when there is a Internet error causing data missing.

**Comment by nkaz001** [comment]
Precisely, when mismatch of update id is detected, the Python version tries to recover by matching update ids from the fetched snapshot. Until recovery is complete, the depth is not reconstructed(not stored). In contrast, the Rust version fetches the snapshot but does not wait for matching update ids. You can choose how to deal with missing update ids when processing stored raw stream data, but recovery can fail. relying on natural refresh is recommended.

**Comment by LJingnan** [comment]
> Precisely, when mismatch of update id is detected, the Python version tries to recover by matching update ids from the fetched snapshot. Until recovery is complete, the depth is not reconstructed(not stored). In contrast, the Rust version fetches the snapshot but does not wait for matching update ids. You can choose how to deal with missing update ids when processing stored raw stream data, but recovery can fail. relying on natural refresh is recommended.

I see, thank you so much.
