### ISSUE TITLE
May I ask about the backtesting data for this project, and what is the average daily profit margin

### ISSUE THREAD

**Issue by fengxiaojie** [nkaz001/hftbacktest#81]

**Comment by nkaz001** [comment]
The data was collected by myself using [this repository](https://github.com/nkaz001/collect-binancefutures) or Tardis. I am preparing an example that shows the entire backtesting process, from data conversion from Tardis data to backtesting making multiple markets based on hft gridtrading.

As for the second question, I'm unsure what that is. Any sources?

**Comment by fengxiaojie** [comment]
I feel that the quality of this project code is too high. Can you ask if the code has any strategies for buying, selling, and closing BTC futures, and what is the approximate winning rate

**Comment by nkaz001** [comment]
i didn't get it. you can start with the example and see how it works and see the figures you want to know by playing with the data and the backtesting result.
