### ISSUE TITLE
About the rate limit of binance

### ISSUE THREAD

**Issue by silkylove** [nkaz001/hftbacktest#95]
I saw that the grid num is 10 or 20 and trade interval is 100ms in your examples. But in binance, there exists some rate limits, such as order limit which limit the number of your new orders under 300/10s and 1200/min. In this case, how can we trade many pairs at the same time? Even if you reduce the trade interval to 1s, it seems still hard to satisfy the order limit.

**Comment by nkaz001** [comment]
In the example, it is assumed that one is a market maker who is eligible for the highest maker rebates, being in the highest tier. They have higher limits, perhaps almost no limits. For more information, please see https://www.binance.com/en/vip-institutional-services and https://www.binance.com/en/support/announcement/binance-updates-usd%E2%93%A2-margined-futures-liquidity-provider-program-2024-06-03-fefc6aa25e0947e2bf745c1c56bea13e
